run:
  name: run_field_ssneb_interpolated
  root: example/field_ssneb_runs/run_field_ssneb_interpolated_tri

path:
  source:
    kind: control_points
    files:
      - /home/gridsan/mzhu/Tools/STEM_TOOL/tsase/example/preprocessed/run_field_ssneb_interpolated_newModel_clamped/control_point_0000.cif
      # - /home/gridsan/mzhu/Tools/STEM_TOOL/tsase/example/preprocessed/run_field_ssneb_interpolated_newModel_clamped/control_point_0008.cif
      - /home/gridsan/mzhu/Tools/STEM_TOOL/tsase/image36.cif
    indices: [0, 63] #[0, 28, 56, 57, 58, 59, 60, 62, 66]
  num_images: 64

model:
  calculator:
    kind: mace_field
    model_path: '/home/gridsan/mzhu/Project/qe_examples/AL_MACE-field/runs/single-model-4nodes_fullData_noDFT3_cont/model/models/cm00.model'
    device: cuda
    head: ft_head
    default_dtype: float64
  charges:
    kind: species_map
    values:
      Pb: 3.9
      Zr: 5.85
      O: -3.25
  field:
    kind: cartesian
    value: [-0.001, -0.005, 0] #[-0.001, -0.005, -0.001] #[-0.0004,  -0.002, -0.0004]
  reference:
    kind: file
    file: /home/gridsan/mzhu/Tools/STEM_TOOL/tsase/examples/structures/R3c_prim_supercell_aligned.cif


band:
  spring: 2.0
  method: ci
  ss: true
  weight: 1
  climbing_images:
    enabled: true
    selection:
      - [1, 31]
      - [32, 62]
    # To force exact image indices instead, use:
    # selection: [18, 45]

constraints:
  filter:
    mask: [0, 0, 0, 0, 0, 0] #
    hydrostatic_strain: false
    constant_volume: false

optimizer:
  kind: fire
  dt: 0.1
  dtmax: 0.20
  maxmove: 0.2
  convergence:
    fmax: 0.001
    max_steps: 2000
  ci_activation:
    force: 0.5

outputs:
  schedule:
    every: 200
    include_final: true
  path_snapshot:
    enabled: true
  diagnostics:
    enabled: true
  energy_profile:
    enabled: true
    emit_csv: true
    emit_png: true
    entries:
      - enthalpy_adjusted
      - intrinsic_energy
      - field_energy
      - polarization_mag
  stem:
    enabled: true

preprocess:
  output_dir: ../../example/preprocessed/run_field_ssneb_interpolated
  relax:
    enabled: true
    fmax: 1e-5
  reference:
    symmetrize: false
    symprec: 1.0
  outputs:
    config_name: run_field_ssneb_interpolated_preprocessed.yaml
